### ISSUE TITLE
Issues from ARIA Working Group review of the ARIA HTML spec document

### ISSUE THREAD

**Issue by accdc** [w3c/html-aria#102] opened 2018-03-15 07:28 UTC
Hello,
I've completed my review of the ARIA HTML spec document, and have found the following areas within the HTML element and role mapping table where issues have been discovered.

For native links, the accepted roles/states/properties column is missing:
scrollbar, slider, combobox, presentation, none

For native buttons , the accepted roles/states/properties column is missing:
scrollbar, slider, combobox, presentation, none

For col and colgroup, the accepted roles/states/properties column is missing:
presentation, none, aria-hidden

For dd, the accepted roles/states/properties column is missing:
presentation, none

For details, the accepted roles/states/properties column is missing:
presentation, none

For dt, the accepted roles/states/properties column is missing:
term, presentation, none
Also within the implicit role column, dt seems like it would map more clearly to role=term.

FYI, within the implicit role column for fieldset, the accessibility tree maps to role=group.

Within the implicit role column for form, not sure if this matters here, but form is supposed to do the same thing as role=region, and only be exposed as a landmark if (1) it includes role=form, or (2) if it includes an explicit label via aria-label or aria-labelledby. This goes back to the mappings meetings with Joseph, Jonie, and Rich when this was decided I think about a year ago. 

For form, the accepted roles/states/properties column is missing:
group, region

For h1 through h6, the accepted roles/states/properties column is missing:
button, checkbox, link, progressbar, radio, scrollbar, slider, spinbutton, switch

For header, the accepted roles/states/properties column is missing:
navigation, region

For iframe, the accepted roles/states/properties column is missing:
region, presentation, none

FYI, within the implicit role column for img + alt="", the accessibility tree maps to role=none.

Within the HTML element column for img + alt="some text", the same rule is applicable for img + title="some text", img + aria-label="some text", and img + aria-labelledby="idref".

For input type=button, the accepted roles/states/properties column is missing:
checkbox, scrollbar, slider, combobox, treeitem

For input type=checkbox, the accepted roles/states/properties column is missing:
treeitem

FYI, within the implicit role column for input type=hidden, the accessibility tree maps to role=none.

For input type=image, the accepted roles/states/properties column is missing:
checkbox, scrollbar, slider, combobox, tab, treeitem

For input type=radio, the accepted roles/states/properties column is missing:
treeitem

For label, the accepted roles/states/properties column is missing:
heading, status

For legend, the accepted roles/states/properties column is missing:
heading, status

For select (with NO multiple attribute and NO size attribute having value greater than 1) (changed), the accepted roles/states/properties column includes an accepted role=menu, which as far as I am aware is incorrect since a menu is not a selectable widget with a value and should not be applied to native select elements.

For svg, the accepted roles/states/properties column is missing:
presentation, none

**Comment by stevefaulkner** [comment] 2018-03-15 07:39
@accdc thanks for your suggestions, will go through them. 
**Note:** 

- The default implicit column mappings are defined in the [HTML AAM](https://w3c.github.io/html-aam/), if you have issue with these you will need to file issues there.
- it is not simply enough to state that "the accepted roles/states/properties column is missing". As a host language HTML can and does limit the allowed roles on elements with meaningful default semantics. If it is requested that a particular role be allowed, then a case needs to be made for why.

**Comment by accdc** [comment] 2018-03-15 18:21
Thanks, I understand, however I don't have time to write a separate markup case for every instance of all of these roles. Speaking personally, our clients at Level Access have had cases for all of these combinations, and all were valid usages of ARIA.

 

I wasn't aware until last week that this document is being used as the guide for the W3C HTML Validator, and that missing roles will be flagged as being invalid usages of ARIA. If this is a misunderstanding on my part, please let me know since this is the primary reason for my objection.

 

As a simple example of this, according to the ARIA HTML spec document, no ARIA roles are allowed to be used on the HTML label element.

 

To my knowledge the ARIA spec makes no claim such as this, so it is unclear where these rules are being deduced from.

 

However, if there is no risk that valid usages of ARIA will be flagged as violations by the HTML Validator, then I have no objections to this.

**Comment by stevefaulkner** [comment] 2018-03-15 18:35
@accdc 
>Speaking personally, our clients at Level Access have had cases for all of these combinations, and all >were valid usages of ARIA.

Your suggested changes will need to be evaluated on a case by case basis, any real world use cases and data you can provide will be taken into consideration when assessing them.

>I wasn't aware until last week that this document is being used as the guide for the W3C HTML Validator, and that missing roles will be flagged as being invalid usages of ARIA

It is not something new, although you were not aware. This has been the case for years /cc @sideshowbarker 

>To my knowledge the ARIA spec makes no claim such as this, so it is unclear where these rules are being deduced from.

The ARIA spec naturally does not make any claims about what is allowed usage in host languages, what it does say is
> Host languages MAY document features that cannot be overridden with WAI-ARIA 
https://www.w3.org/TR/wai-aria-1.1/#host_general_conflict

Which is what ARIA in HTML does for the HTML specification. The rules have been developed over the past 8 years.

**Comment by accdc** [comment] 2018-03-15 19:30
So, if I understand correctly, are you saying that the HTML Validator will flag any ARIA role present on a label element as being invalid?

**Comment by stevefaulkner** [comment] 2018-03-15 20:25
>So, if I understand correctly, are you saying that the HTML Validator will
flag any ARIA role present on a label element as being invalid?

yes, the aim of the conformance requirements is to deter authors from
misusing HTML elements that have strong semantics or behaviour. Can you
provide a use case for adding roles to the label element, that could not be
easily fulfilled using a span?

--

Regards

SteveF
Current Standards Work @W3C
<http://www.paciellogroup.com/blog/2015/03/current-standards-work-at-w3c/>

**Comment by accdc** [comment] 2018-03-15 21:08
Yes, because nothing in the ARIA spec says that developers cannot do so. All of the roles I mentioned are simply those that I know of personally, but there are countless others not mentioned.

 

E.G It is perfectly valid to include role=checkbox on a label element that includes a hidden checkbox element so that the simulated checkbox control is focusable and interactive and toggles aria-checked while the result of this is reflected within the hidden checkbox for form submission.

 

There are so many examples of this with various markup structures that, if the HTML Validator is going to be flagging all such instances as being invalid, then the W3C HTML Validator cannot be trusted to provide accurate ARIA related information.

**Comment by sideshowbarker** [comment] 2018-03-15 22:47
> As a simple example of this, according to the ARIA HTML spec document, no ARIA roles are allowed to be used on the HTML label element.
> 
> To my knowledge the ARIA spec makes no claim such as this

Right. That’s because by design, the ARIA spec makes no normative claims about what roles are allowed HTML elements, nor on elements in any other host language — instead it says that’s something which is left up to host language specifications to define.

You do understand that it’s impossible to implement validator support for ARIA in HTML based simply on the ARIA spec, right?

**Comment by accdc** [comment] 2018-03-16 02:16
“You do understand that it’s impossible to implement validator support for ARIA in HTML based simply on the ARIA spec, right?”

 

Is this question for me?

 

I’m not talking about HTML validation here, but ARIA usage validation. These two are not the same as you state. 

 

From what I gather from this discussion, this ARIA HTML spec appears to be stating that the normative rules for correct ARIA usage, are not contained within the ARIA 1.1 specification, and that a different spec document is responsible for determining this instead. However this determination directly contradicts the ARIA 1.1 specification.

**Comment by LJWatson** [comment] 2018-03-16 14:18
@accdc accdc
When you reply to these comments by email, can you please clear the entire content of the original email before you do? Otherwise the Github discussion gets cluttered with quoted email content. Thanks.

**Comment by LJWatson** [comment] 2018-03-16 14:24
@accdc accdc
<I’m not talking about HTML validation here, but ARIA usage validation. These two are not the same as you state.<

This is about HTML validation; specifically how ARIA may be used within a conforming HTML document.

<From what I gather from this discussion, this ARIA HTML spec appears to be stating that the normative rules for correct ARIA usage, are not contained within
the ARIA 1.1 specification, and that a different spec document is responsible for determining this instead.<

This is correct. As Steve notes above, ARIA leaves such requirements up to the host language. These requirements for ARIA in HTML conformance have existed since HTML5 was released in 2014.

<However this determination directly contradicts
the ARIA 1.1 specification.<

Can you provide an example where there is a contradiction, bearing in mind that the responsibility for determining whether something is conforming in HTML rests soley with the HTML spec?

**Comment by scottaohara** [comment] 2020-02-15 05:50
I'm going to close this issue.

Some requested considerations from this issue have been incorporated into the spec already.  Some remain that would need tests & use cases before further consideration.

But I have created four new issues from requests in this comment for further consideration.

**Closed as completed by scottaohara** 2020-02-15 05:50 UTC
